"""Fix relationship between entries and emotions

Revision ID: a594708b3ef7
Revises: f2058cad2bb3
Create Date: 2023-10-07 09:29:22.172891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a594708b3ef7'
down_revision: Union[str, None] = 'f2058cad2bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('emotions_entry_id_fkey', 'emotions', type_='foreignkey')
    op.create_foreign_key(None, 'emotions', 'entries', ['entry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emotions', type_='foreignkey')
    op.create_foreign_key('emotions_entry_id_fkey', 'emotions', 'entries', ['entry_id'], ['id'])
    # ### end Alembic commands ###
