"""Add tables Entries and Emotions

Revision ID: f2058cad2bb3
Revises: de70277d0e42
Create Date: 2023-10-03 20:33:22.960803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2058cad2bb3'
down_revision: Union[str, None] = 'de70277d0e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('situation', sa.String(), nullable=False),
    sa.Column('thoughts_at_moment', sa.String(), nullable=False),
    sa.Column('reaction', sa.String(), nullable=False),
    sa.Column('helped_thoughts', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('emotion', sa.Enum('IRRITATION', 'ANGER', 'RAGE', 'FURY', 'EXCITEMENT', 'ANXIETY', 'FEAR', 'HORROR', 'SADNESS', 'MELANCHOLY', 'SORROW', 'YEARNING', 'DESPAIR', 'GRIEF', 'EMBARRASSMENT', 'SHAME', 'GUILT', 'JEALOUSY', 'ENVY', 'RESENTMENT', 'DISAPPOINTMENT', 'INDIGNATION', 'CONTEMPT', 'DISGUST', 'HATRED', name='emotionsenum'), nullable=False),
    sa.Column('rate_at_moment', sa.Integer(), nullable=False),
    sa.Column('rate_after', sa.Integer(), nullable=False),
    sa.CheckConstraint('(rate_at_moment > 0 AND rate_at_moment <= 10) AND (rate_after > 0 AND rate_after <= 10)'),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emotions')
    op.drop_table('entries')
    # ### end Alembic commands ###
